const { default: mongoose } = require("mongoose");

const hardware = mongoose.Schema({
  SKU: { required: true, type: String, unique: true },
  title: { required: true, type: String },
  category_name: { type: String },
  category_id: { type: String },
  sub_category_name: { type: String },
  sub_category_id: { type: String },
  hardware_image: { required: true, type: Array, default: [] },
  warehouse: { type: Array, default: [] },
  bangalore_stock: { type: Number },
  jodhpur_stock: { type: Number },
  manufacturing_time: { required: true, type: String },
  returnDays: { type: Number },
  COD: { type: Boolean },
  returnable: { type: Boolean },
  quantity: { type: Number },
  package_length: { type: Number },
  package_height: { type: Number },
  package_breadth: { type: Number },
  unit: { type: String },
  selling_price: { type: Number },
  showroom_price: { type: Number },
  polish_time: { type: Number },
  restocking_time: { type: Number, default: 0 },
  selling_points: { type: Array, default: [] },
  seo_title: { type: String },
  seo_description: { type: String },
  seo_keyword: { type: String },
  hardware_polish: { type: String, default: "None" },
  min_quantity: { type: Number, default: 1 },
  continue_selling: { type: Boolean, default: false },
  online_store: { type: Boolean, default: true },
  mobile_store: { type: Boolean, default: true },
  status: { type: Boolean, default: true },
  primary_material: { type: Array, default: [] },
  primary_material_name: { type: String },
  discount_limit: { type: Number, default: 0 },
  tax_rate: { type: Number, default: 0 },
  weight: { type: Number, default: 0 },
  package_weight: { type: Number, default: 0 },
  specification_image: { type: String, default: "" },
  featured_image: { type: String, default: "" },
});

module.exports = mongoose.model("hardware", hardware);
