const { default: mongoose } = require("mongoose");
const { stringify } = require("nodemon/lib/utils");

const product = mongoose.Schema({
    SKU : {required : true, type : String, unique: true},
    product_title : {required : true, type : String},
    category_name : {required : true, type : String},
    sub_category_name : {required : true, type : String},
    product_description : {required : true, type : String},
    seo_title : {required : true, type : String},
    seo_description : {required : true, type : String},
    product_image : {required : true, type : Array},
    featured_image : {required : true, type : Array},
    primary_material : {required : true, type : String},
    secondary_marterial : { type : String},
    secondary_marterial_weight : {type :  Number},
    length_main : { type : Number},
    breadth : { type : Number},
    height : { type : Number},
    weight : { type : String},
    polish : { type : String},
    hinge : { type : String},
    knob : { type : String},
    handle : { type : String},
    door : { type : String},
    fitting : { type : String},
    selling_points : {required : true, type : String},
    top_size : {type : Number},
    dial_size : { type : Number},
    seating_size_width : { type : Number},
    seating_size_depth : { type : Number},
    seating_size_height : { type : Number},
    weight_capacity : { type : String},
    wall_hanging : { type : String},
    assembly_required : { type : String},
    assembly_part : { type : Number},
    legs : { type : String},
    mirror : { type : String},
    mirror_length : { type : String},
    mirror_width : { type : String},
    silver : { type : String},
    silver_weight : { type : Number},
    joints : { type : String},
    wheel : { type : String},
    trolley : { type : String},
    trolly_matterial : { type : String},
    rotating_seats : { type : Boolean},
    eatable_oil_polish : { type : Boolean},
    no_chemical : { type : Boolean},
    lean_back : { type : Boolean},
    weaving : { type : Boolean},
    not_suitable_for_Micro_Dish : { type : Boolean},
    tilt_top : { type : Boolean},
    indise_compartments : { type : Boolean},
    stackable : { type : Boolean},
    MRP : {required : true, type : Number},
    tax_rate : {required : true, type : Number},
    selling_price : {required : true, type : Number},
    discount_limit : {required : true, type : Number},
    dispatch_time : {required : true, type : String},
})

module.exports = mongoose.model('products',product);